import Head from 'next/head';
import ContactBar from '../components/ContactBar/ContactBar';
import Navbar from '../components/Navbar/Navbar';

export default function Home() {
  return (
    <>
      <Head>
        <title>BoomBalloonLV | Home</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <ContactBar />
      <Navbar />
    </>
  );
}
