import Head from 'next/head';
import PageWrapper from '../components/PageWrapper/PageWrapper';
import ContactBar from '../components/ContactBar/ContactBar';
import Banner from '../components/Banner/Banner';

export default function Home() {
  return (
    <>
      <Head>
        <title>BoomBalloonLV | Home</title>
        <meta name='description' content='Generated by create next app' />
        <meta
          name='description'
          property='description'
          content='BoomBalloonLV | Custom Balloons Decoration in Las Vegas | Boomballoonlv offers custom balloons decoration for wedding, birthday, babyshower, graduation, corporate events in Las Vegas and Henderson, Nevada.'
        />
        <meta
          name='description'
          property='og:description'
          content='BoomBalloonLV | Custom Balloons Decoration in Las Vegas | Boomballoonlv offers custom balloons decoration for wedding, birthday, babyshower, graduation, corporate events in Las Vegas and Henderson, Nevada.'
        />
      </Head>
      <PageWrapper>
        <ContactBar />
        <Banner />
      </PageWrapper>
    </>
  );
}
